services:
  - type: web
    name: Ajor
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        value: 8985557733:AAGN4ZraC4fnc2PCm7eAOwAV-TkL0yl4L-Y
      - key: MONGODB_URI
        value: mongodb+srv://gorgalikhanzebel_db_user:ZZ8O2D3VhzPgqHxZ@cluster0.y56mkjn.mongodb.net/?appName=Cluster0
